# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s

options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'

steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20210917-12df099d55'
    entrypoint: bash
    dir: ./util-images
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - HOME=/root  # for docker buildx
      - WHAT=$_WHAT
    args:
    - -c
    - |
      gcloud auth configure-docker && \
      make push
substitutions:
  # _WHAT will contain the image name to be built and published to the staging registry.
  _WHAT: 'all'